name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildDebug:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create local.properties file in data module
      env:
        TMDB_BEARER_TOKEN: ${{ secrets.TMDB_BEARER_TOKEN }}
      run: echo "TMDB_BEARER_TOKEN=\"$TMDB_BEARER_TOKEN\"" > data/local.properties
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
          name: apk-files
          path: app/build/outputs/apk/debug/*.apk
    - name: Remove local.properties file from data module
      run: rm data/local.properties
